name: punx

channels:
  - defaults
  - conda-forge

dependencies:
  - h5py >=3
  - hdf5plugin
  - lxml
  - numpy
  - python=3
  - pip
  - pyqt
  - pyRestTable
  - requests
  - sip
  - sphinx
  - versioneer
  - sphinx_rtd_theme
