.. _hierarchy:
.. index:: hierarchy

User interface: subcommand: **hierarchy**
#########################################

-tba-

..
	show NeXus base class hierarchy

	.. tip:: This command only prints a line referring to the
	   on-line documentation.  See that directly here:
	   :ref:`NeXus base class hierarchy <fig.base.class.hierarchy>`
	   
	   This figure was generated by an anlysis of the NeXus NXDL definitions
	   from the GitHub repository.


	View the    :ref:`NeXus base class hierarchy <fig.base.class.hierarchy>` 


	.. rubric:: command line help

	.. code-block:: console

	   console> punx hierarchy -h
	   punx hierarchy -h
	   usage: punx hierarchy [-h] something
	   
	   positional arguments:
	     something   something help
	   
	   optional arguments:
	     -h, --help  show this help message and exit
